-- Plant Brain :: 02_load.sql
-- Loads data_gen/out/*.csv into RAW. Re-running is a full reset of RAW (demo reset).
--
-- Step 1 (client only: SnowSQL / snow CLI / scripts/sf.py, run from repo root):
--   PUT uploads the local CSVs to the stage. Snowsight can't run PUT; instead upload the
--   9 CSVs through Snowsight: Data > Databases > PLANT_BRAIN > RAW > Stages > LANDING > + Files,
--   then run this file from the TRUNCATE section onwards.
-- Patterns accept both plain .csv (Snowsight upload) and .csv.gz (PUT auto-compress).

USE ROLE PB_ROLE;
USE WAREHOUSE PB_WH;
USE SCHEMA PLANT_BRAIN.RAW;

PUT 'file://data_gen/out/*.csv' @RAW.LANDING AUTO_COMPRESS = TRUE OVERWRITE = TRUE;

-- ---- Step 2: load (safe to run in Snowsight) ------------------------------
TRUNCATE TABLE IF EXISTS ASSETS;
TRUNCATE TABLE IF EXISTS FAILURE_MODES;
TRUNCATE TABLE IF EXISTS TECHNICIANS;
TRUNCATE TABLE IF EXISTS SPARE_PARTS;
TRUNCATE TABLE IF EXISTS ASSET_CHANGES;
TRUNCATE TABLE IF EXISTS WORK_ORDERS;
TRUNCATE TABLE IF EXISTS HANDOVER_NOTES;
TRUNCATE TABLE IF EXISTS PRODUCTION_LOG;
TRUNCATE TABLE IF EXISTS SENSOR_READINGS;

COPY INTO ASSETS          FROM @RAW.LANDING PATTERN = '(.*/)?assets[.]csv([.]gz)?'          FORCE = TRUE ON_ERROR = ABORT_STATEMENT;
COPY INTO FAILURE_MODES   FROM @RAW.LANDING PATTERN = '(.*/)?failure_modes[.]csv([.]gz)?'   FORCE = TRUE ON_ERROR = ABORT_STATEMENT;
COPY INTO TECHNICIANS     FROM @RAW.LANDING PATTERN = '(.*/)?technicians[.]csv([.]gz)?'     FORCE = TRUE ON_ERROR = ABORT_STATEMENT;
COPY INTO SPARE_PARTS     FROM @RAW.LANDING PATTERN = '(.*/)?spare_parts[.]csv([.]gz)?'     FORCE = TRUE ON_ERROR = ABORT_STATEMENT;
COPY INTO ASSET_CHANGES   FROM @RAW.LANDING PATTERN = '(.*/)?asset_changes[.]csv([.]gz)?'   FORCE = TRUE ON_ERROR = ABORT_STATEMENT;
COPY INTO WORK_ORDERS     FROM @RAW.LANDING PATTERN = '(.*/)?work_orders[.]csv([.]gz)?'     FORCE = TRUE ON_ERROR = ABORT_STATEMENT;
COPY INTO HANDOVER_NOTES  FROM @RAW.LANDING PATTERN = '(.*/)?handover_notes[.]csv([.]gz)?'  FORCE = TRUE ON_ERROR = ABORT_STATEMENT;
COPY INTO PRODUCTION_LOG  FROM @RAW.LANDING PATTERN = '(.*/)?production_log[.]csv([.]gz)?'  FORCE = TRUE ON_ERROR = ABORT_STATEMENT;
COPY INTO SENSOR_READINGS FROM @RAW.LANDING PATTERN = '(.*/)?sensor_readings[.]csv([.]gz)?' FORCE = TRUE ON_ERROR = ABORT_STATEMENT;

-- Expected: 12 / 10 / 8 / 40 / 15 / 144 / 295 / 2690 / 311040
SELECT 'ASSETS' AS tbl, COUNT(*) AS n FROM ASSETS UNION ALL
SELECT 'FAILURE_MODES', COUNT(*) FROM FAILURE_MODES UNION ALL
SELECT 'TECHNICIANS', COUNT(*) FROM TECHNICIANS UNION ALL
SELECT 'SPARE_PARTS', COUNT(*) FROM SPARE_PARTS UNION ALL
SELECT 'ASSET_CHANGES', COUNT(*) FROM ASSET_CHANGES UNION ALL
SELECT 'WORK_ORDERS', COUNT(*) FROM WORK_ORDERS UNION ALL
SELECT 'HANDOVER_NOTES', COUNT(*) FROM HANDOVER_NOTES UNION ALL
SELECT 'PRODUCTION_LOG', COUNT(*) FROM PRODUCTION_LOG UNION ALL
SELECT 'SENSOR_READINGS', COUNT(*) FROM SENSOR_READINGS;
