-- Plant Brain :: 07_semantic_view.sql
-- GENERATED by scripts/render_semantic_view.py from app/plant_brain/verified_queries.py. Do not edit.
-- Semantic view for Cortex Analyst over assets, OEE, work orders, downtime, technicians and parts.
-- The same verified queries power the deterministic analytics route in Ask the Plant (both modes).

USE ROLE PB_ROLE;
USE WAREHOUSE PB_WH;
USE SCHEMA PLANT_BRAIN.CORE;

CREATE OR REPLACE SEMANTIC VIEW CORE.PLANT_SEMANTIC_VIEW
  TABLES (
    assets AS PLANT_BRAIN.RAW.ASSETS
      PRIMARY KEY (asset_id)
      WITH SYNONYMS ('machines', 'equipment')
      COMMENT = 'The 12 critical assets across lines L1-L3',
    technicians AS PLANT_BRAIN.RAW.TECHNICIANS
      PRIMARY KEY (technician_id)
      WITH SYNONYMS ('techs', 'maintenance staff')
      COMMENT = 'Maintenance technicians; retiring_2027 flags knowledge-loss risk',
    oee_daily AS PLANT_BRAIN.CORE.OEE_DAILY
      PRIMARY KEY (asset_id, oee_date)
      COMMENT = 'OEE per asset per production day',
    line_oee AS PLANT_BRAIN.CORE.OEE_LINE_DAILY
      PRIMARY KEY (line_id, oee_date)
      COMMENT = 'OEE per line per production day',
    work_orders AS PLANT_BRAIN.RAW.WORK_ORDERS
      PRIMARY KEY (wo_id)
      WITH SYNONYMS ('jobs', 'breakdowns', 'repairs')
      COMMENT = 'Maintenance work orders; CORRECTIVE = breakdown repair',
    spare_parts AS PLANT_BRAIN.RAW.SPARE_PARTS
      PRIMARY KEY (part_id)
      WITH SYNONYMS ('spares', 'inventory')
      COMMENT = 'Spare parts stock, reorder points and lead times'
  )
  RELATIONSHIPS (
    oee_to_asset AS oee_daily (asset_id) REFERENCES assets,
    wo_to_asset AS work_orders (asset_id) REFERENCES assets,
    wo_to_technician AS work_orders (technician_id) REFERENCES technicians
  )
  FACTS (
    oee_daily.planned_min AS planned_min,
    oee_daily.run_min AS run_min,
    oee_daily.oee_downtime_min AS downtime_min,
    oee_daily.total_count AS total_count,
    oee_daily.good_count AS good_count,
    oee_daily.scrap_count AS scrap_count,
    work_orders.wo_downtime_min AS downtime_min
      COMMENT = 'Minutes the asset was down for this work order',
    work_orders.repair_minutes AS DATEDIFF('minute', reported_at, closed_at),
    spare_parts.stock_qty AS stock_qty,
    spare_parts.reorder_point AS reorder_point,
    spare_parts.lead_time_days AS lead_time_days
  )
  DIMENSIONS (
    assets.asset_id AS asset_id,
    assets.asset_type AS asset_type,
    assets.asset_line_id AS line_id,
    technicians.full_name AS full_name WITH SYNONYMS = ('technician', 'technician name'),
    technicians.seniority AS seniority,
    technicians.retiring_2027 AS retiring_2027,
    oee_daily.oee_date AS oee_date,
    oee_daily.oee_line_id AS line_id,
    line_oee.line_id AS line_id WITH SYNONYMS = ('line', 'production line'),
    line_oee.line_oee_date AS oee_date,
    work_orders.wo_type AS wo_type,
    work_orders.failure_mode_code AS failure_mode_code WITH SYNONYMS = ('downtime cause', 'failure mode'),
    work_orders.reported_at AS reported_at,
    work_orders.wo_asset_id AS asset_id,
    spare_parts.part_id AS part_id,
    spare_parts.description AS description
  )
  METRICS (
    oee_daily.avg_oee AS AVG(oee) COMMENT = 'Average daily OEE (Availability x Performance x Quality)',
    oee_daily.avg_availability AS AVG(availability),
    oee_daily.avg_performance AS AVG(performance),
    oee_daily.avg_quality AS AVG(quality),
    line_oee.avg_line_oee AS AVG(oee),
    work_orders.breakdowns AS COUNT(wo_id),
    work_orders.total_downtime_min AS SUM(work_orders.wo_downtime_min),
    work_orders.mttr_hours AS AVG(work_orders.repair_minutes) / 60 COMMENT = 'Mean time to repair, hours',
    spare_parts.parts_below_reorder AS COUNT_IF(stock_qty <= reorder_point)
  )
  COMMENT = 'Plant Brain (synthetic data): OEE, downtime, MTTR, parts'
  AI_SQL_GENERATION 'The dataset ends on 2026-08-31. Interpret "last week", "this month" relative to the latest date in the data, not CURRENT_DATE. Breakdowns are work orders with wo_type = CORRECTIVE.'
  AI_VERIFIED_QUERIES (
    oee_by_line_last_week AS (
      QUESTION 'What was the OEE for each line last week?'
      VERIFIED_AT 1790726400
      ONBOARDING_QUESTION TRUE
      SQL 'SELECT line_id, ROUND(AVG(oee), 4) AS avg_oee, ROUND(AVG(availability), 4) AS avg_availability,
       ROUND(AVG(performance), 4) AS avg_performance, ROUND(AVG(quality), 4) AS avg_quality
FROM line_oee
WHERE oee_date > DATEADD(''day'', -7, (SELECT MAX(oee_date) FROM line_oee))
GROUP BY line_id ORDER BY line_id'
    ),
    top_downtime_causes_this_month AS (
      QUESTION 'What are the top downtime causes this month?'
      VERIFIED_AT 1790726400
      ONBOARDING_QUESTION FALSE
      SQL 'SELECT COALESCE(failure_mode_code, ''UNCLASSIFIED'') AS failure_mode, COUNT(*) AS breakdowns,
       SUM(downtime_min) AS downtime_min
FROM work_orders
WHERE wo_type = ''CORRECTIVE''
  AND reported_at >= DATE_TRUNC(''month'', (SELECT MAX(reported_at) FROM work_orders WHERE wo_type = ''CORRECTIVE''))
GROUP BY COALESCE(failure_mode_code, ''UNCLASSIFIED'') ORDER BY downtime_min DESC'
    ),
    mttr_by_technician AS (
      QUESTION 'What is the MTTR by technician?'
      VERIFIED_AT 1790726400
      ONBOARDING_QUESTION FALSE
      SQL 'SELECT t.full_name AS technician, COUNT(*) AS corrective_jobs,
       ROUND(AVG(DATEDIFF(''minute'', w.reported_at, w.closed_at)) / 60.0, 2) AS mttr_hours
FROM work_orders w JOIN technicians t ON t.technician_id = w.technician_id
WHERE w.wo_type = ''CORRECTIVE'' AND w.closed_at IS NOT NULL
GROUP BY t.full_name ORDER BY mttr_hours'
    ),
    parts_at_risk_of_stockout AS (
      QUESTION 'Which spare parts are at risk of stockout?'
      VERIFIED_AT 1790726400
      ONBOARDING_QUESTION TRUE
      SQL 'SELECT part_id, description, stock_qty, reorder_point, lead_time_days
FROM spare_parts
WHERE stock_qty <= reorder_point
ORDER BY stock_qty - reorder_point, lead_time_days DESC'
    ),
    lowest_oee_assets_last_week AS (
      QUESTION 'Which assets had the lowest OEE last week?'
      VERIFIED_AT 1790726400
      ONBOARDING_QUESTION FALSE
      SQL 'SELECT asset_id, line_id, ROUND(AVG(oee), 4) AS avg_oee, SUM(downtime_min) AS downtime_min
FROM oee_daily
WHERE oee_date > DATEADD(''day'', -7, (SELECT MAX(oee_date) FROM oee_daily))
GROUP BY asset_id, line_id ORDER BY avg_oee LIMIT 5'
    ),
    downtime_by_asset AS (
      QUESTION 'How much breakdown downtime did each asset have?'
      VERIFIED_AT 1790726400
      ONBOARDING_QUESTION FALSE
      SQL 'SELECT asset_id, COUNT(*) AS breakdowns, SUM(downtime_min) AS downtime_min
FROM work_orders
WHERE wo_type = ''CORRECTIVE''
GROUP BY asset_id ORDER BY downtime_min DESC'
    ),
    breakdowns_by_asset_and_failure_mode AS (
      QUESTION 'How many times has each asset failed, and why?'
      VERIFIED_AT 1790726400
      ONBOARDING_QUESTION FALSE
      SQL 'SELECT asset_id, COALESCE(failure_mode_code, ''UNCLASSIFIED'') AS failure_mode, COUNT(*) AS breakdowns,
       SUM(downtime_min) AS downtime_min
FROM work_orders
WHERE wo_type = ''CORRECTIVE''
GROUP BY asset_id, COALESCE(failure_mode_code, ''UNCLASSIFIED'') ORDER BY asset_id, breakdowns DESC'
    ),
    weekly_plant_oee_trend AS (
      QUESTION 'What is the weekly OEE trend for the plant?'
      VERIFIED_AT 1790726400
      ONBOARDING_QUESTION FALSE
      SQL 'SELECT DATE_TRUNC(''week'', oee_date) AS week_start, ROUND(AVG(oee), 4) AS avg_oee
FROM line_oee
GROUP BY DATE_TRUNC(''week'', oee_date) ORDER BY week_start'
    ),
    jobs_done_by_retiring_technicians AS (
      QUESTION 'Which breakdown repairs were done by technicians retiring in 2027?'
      VERIFIED_AT 1790726400
      ONBOARDING_QUESTION FALSE
      SQL 'SELECT t.full_name AS technician, w.asset_id, COUNT(*) AS corrective_jobs
FROM work_orders w JOIN technicians t ON t.technician_id = w.technician_id
WHERE w.wo_type = ''CORRECTIVE'' AND t.retiring_2027
GROUP BY t.full_name, w.asset_id ORDER BY corrective_jobs DESC'
    ),
    scrap_by_asset_last_week AS (
      QUESTION 'Which assets produced the most scrap last week?'
      VERIFIED_AT 1790726400
      ONBOARDING_QUESTION FALSE
      SQL 'SELECT asset_id, SUM(scrap_count) AS scrap_count, ROUND(AVG(quality), 4) AS avg_quality
FROM oee_daily
WHERE oee_date > DATEADD(''day'', -7, (SELECT MAX(oee_date) FROM oee_daily))
GROUP BY asset_id ORDER BY scrap_count DESC'
    )
  );
