"""Render snowflake/07_semantic_view.sql from app/plant_brain/verified_queries.py (single source).

    python scripts/render_semantic_view.py          # write the file
    python scripts/render_semantic_view.py --check  # fail if the committed file is out of date
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "app"))
from plant_brain.verified_queries import VERIFIED_QUERIES, render  # noqa: E402

VERIFIED_AT = 1790726400  # 2026-09-30, fixed so the output is reproducible

HEAD = """-- Plant Brain :: 07_semantic_view.sql
-- GENERATED by scripts/render_semantic_view.py from app/plant_brain/verified_queries.py. Do not edit.
-- Semantic view for Cortex Analyst over assets, OEE, work orders, downtime, technicians and parts.
-- The same verified queries power the deterministic analytics route in Ask the Plant (both modes).

USE ROLE PB_ROLE;
USE WAREHOUSE PB_WH;
USE SCHEMA PLANT_BRAIN.CORE;

CREATE OR REPLACE SEMANTIC VIEW CORE.PLANT_SEMANTIC_VIEW
  TABLES (
    assets AS PLANT_BRAIN.RAW.ASSETS
      PRIMARY KEY (asset_id)
      WITH SYNONYMS ('machines', 'equipment')
      COMMENT = 'The 12 critical assets across lines L1-L3',
    technicians AS PLANT_BRAIN.RAW.TECHNICIANS
      PRIMARY KEY (technician_id)
      WITH SYNONYMS ('techs', 'maintenance staff')
      COMMENT = 'Maintenance technicians; retiring_2027 flags knowledge-loss risk',
    oee_daily AS PLANT_BRAIN.CORE.OEE_DAILY
      PRIMARY KEY (asset_id, oee_date)
      COMMENT = 'OEE per asset per production day',
    line_oee AS PLANT_BRAIN.CORE.OEE_LINE_DAILY
      PRIMARY KEY (line_id, oee_date)
      COMMENT = 'OEE per line per production day',
    work_orders AS PLANT_BRAIN.RAW.WORK_ORDERS
      PRIMARY KEY (wo_id)
      WITH SYNONYMS ('jobs', 'breakdowns', 'repairs')
      COMMENT = 'Maintenance work orders; CORRECTIVE = breakdown repair',
    spare_parts AS PLANT_BRAIN.RAW.SPARE_PARTS
      PRIMARY KEY (part_id)
      WITH SYNONYMS ('spares', 'inventory')
      COMMENT = 'Spare parts stock, reorder points and lead times'
  )
  RELATIONSHIPS (
    oee_to_asset AS oee_daily (asset_id) REFERENCES assets,
    wo_to_asset AS work_orders (asset_id) REFERENCES assets,
    wo_to_technician AS work_orders (technician_id) REFERENCES technicians
  )
  FACTS (
    oee_daily.planned_min AS planned_min,
    oee_daily.run_min AS run_min,
    oee_daily.oee_downtime_min AS downtime_min,
    oee_daily.total_count AS total_count,
    oee_daily.good_count AS good_count,
    oee_daily.scrap_count AS scrap_count,
    work_orders.wo_downtime_min AS downtime_min
      COMMENT = 'Minutes the asset was down for this work order',
    work_orders.repair_minutes AS DATEDIFF('minute', reported_at, closed_at),
    spare_parts.stock_qty AS stock_qty,
    spare_parts.reorder_point AS reorder_point,
    spare_parts.lead_time_days AS lead_time_days
  )
  DIMENSIONS (
    assets.asset_id AS asset_id,
    assets.asset_type AS asset_type,
    assets.asset_line_id AS line_id,
    technicians.full_name AS full_name WITH SYNONYMS = ('technician', 'technician name'),
    technicians.seniority AS seniority,
    technicians.retiring_2027 AS retiring_2027,
    oee_daily.oee_date AS oee_date,
    oee_daily.oee_line_id AS line_id,
    line_oee.line_id AS line_id WITH SYNONYMS = ('line', 'production line'),
    line_oee.line_oee_date AS oee_date,
    work_orders.wo_type AS wo_type,
    work_orders.failure_mode_code AS failure_mode_code WITH SYNONYMS = ('downtime cause', 'failure mode'),
    work_orders.reported_at AS reported_at,
    work_orders.wo_asset_id AS asset_id,
    spare_parts.part_id AS part_id,
    spare_parts.description AS description
  )
  METRICS (
    oee_daily.avg_oee AS AVG(oee) COMMENT = 'Average daily OEE (Availability x Performance x Quality)',
    oee_daily.avg_availability AS AVG(availability),
    oee_daily.avg_performance AS AVG(performance),
    oee_daily.avg_quality AS AVG(quality),
    line_oee.avg_line_oee AS AVG(oee),
    work_orders.breakdowns AS COUNT(wo_id),
    work_orders.total_downtime_min AS SUM(work_orders.wo_downtime_min),
    work_orders.mttr_hours AS AVG(work_orders.repair_minutes) / 60 COMMENT = 'Mean time to repair, hours',
    spare_parts.parts_below_reorder AS COUNT_IF(stock_qty <= reorder_point)
  )
  COMMENT = 'Plant Brain (synthetic data): OEE, downtime, MTTR, parts'
  AI_SQL_GENERATION 'The dataset ends on 2026-08-31. Interpret "last week", "this month" relative to the latest date in the data, not CURRENT_DATE. Breakdowns are work orders with wo_type = CORRECTIVE.'
  AI_VERIFIED_QUERIES (
"""


def sql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def build() -> str:
    vqs = []
    for vq in VERIFIED_QUERIES:
        vqs.append(f"""    {vq['name']} AS (
      QUESTION {sql_str(vq['question'])}
      VERIFIED_AT {VERIFIED_AT}
      ONBOARDING_QUESTION {'TRUE' if vq['name'] in ('oee_by_line_last_week', 'parts_at_risk_of_stockout') else 'FALSE'}
      SQL {sql_str(render(vq, logical=True))}
    )""")
    return HEAD + ",\n".join(vqs) + "\n  );\n"


if __name__ == "__main__":
    out = ROOT / "snowflake" / "07_semantic_view.sql"
    text = build()
    if "--check" in sys.argv:
        ok = out.exists() and out.read_text() == text
        print("07_semantic_view.sql is up to date" if ok else "07_semantic_view.sql is STALE: re-run without --check")
        sys.exit(0 if ok else 1)
    out.write_text(text)
    print(f"wrote {out} ({len(VERIFIED_QUERIES)} verified queries)")
